In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
dataset = pd.read_csv('insurance_pre.csv')

In [33]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [34]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [35]:
 dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [36]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [42]:
 from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [43]:
 from sklearn.ensemble import RandomForestRegressor

In [44]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': [1.0, 'sqrt', 'log2'],
    'n_estimators': [10, 100]
}

grid = GridSearchCV(
    RandomForestRegressor(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)

# Fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [1.0, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [47]:
# print best parameter after tuning
# Get the best parameters
print(grid.best_params_)

# Get cross-validation results
re = grid.cv_results_

# Predict the test data
grid_predictions = grid.predict(X_test)

# Calculate R2 score
from sklearn.metrics import r2_score

r_score = r2_score(y_test, grid_predictions)

print(
    "The R2 score for the best parameters {}: {}".format(
        grid.best_params_, r_score
    )
)

{'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}
The R2 score for the best parameters {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8663406019326709

In [48]:
 table=pd.DataFrame.from_dict(re)

In [49]:
 table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.144514,0.016002,0.006603,0.001839,squared_error,1.0,10,"{'criterion': 'squared_error', 'max_features':...",0.788245,0.736780,0.823314,0.749734,0.758374,0.771289,0.031037,11
1,0.641715,0.078219,0.022198,0.008938,squared_error,1.0,100,"{'criterion': 'squared_error', 'max_features':...",0.805283,0.742564,0.830150,0.802668,0.767351,0.789603,0.030882,5
2,0.083185,0.009617,0.006576,0.002329,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.793165,0.753647,0.813803,0.813801,0.748596,0.784602,0.028401,7
3,0.551747,0.039034,0.019350,0.003779,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.805836,0.768898,0.841786,0.835524,0.760968,0.802602,0.033163,1
4,0.059322,0.007457,0.005039,0.001815,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.775753,0.742322,0.827940,0.801864,0.742152,0.778006,0.033546,8
5,0.510418,0.063360,0.017321,0.000612,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.809023,0.764118,0.837709,0.828385,0.770713,0.801990,0.029781,2
6,0.227605,0.016280,0.003856,0.001224,absolute_error,1.0,10,"{'criterion': 'absolute_error', 'max_features'...",0.771882,0.760342,0.813570,0.780453,0.735968,0.772443,0.025428,10
7,1.719993,0.057873,0.014788,0.002249,absolute_error,1.0,100,"{'criterion': 'absolute_error', 'max_features'...",0.787438,0.770098,0.814344,0.802561,0.760913,0.787071,0.019780,6
8,0.129143,0.016426,0.003745,0.000687,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.793025,0.745460,0.807465,0.817141,0.726177,0.777853,0.035694,9
9,1.135167,0.025976,0.015294,0.001933,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.795974,0.774505,0.837295,0.822706,0.765523,0.799201,0.027416,4
10,0.118676,0.010077,0.003844,0.000235,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.754096,0.745487,0.809490,0.806514,0.740285,0.771174,0.030406,12
11,1.106358,0.032014,0.014600,0.001173,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.808568,0.772375,0.840769,0.824817,0.762127,0.801731,0.030113,3

In [50]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [51]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[48322.9686647]